grafana:
  enabled: false
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector:
      matchLabels:
        monitoring: "true"
    serviceMonitorNamespaceSelector:
      matchLabels:
        monitoring: "true"
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
